### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short

### ISSUE THREAD

**Issue by persistz** [piaozhx/DockerMonitor#11]
### 1. 查明问题原因
程序无法跑通有多种原因, 请严格走以下步骤:
1. 提问之前你做过研究吗？你是否说明了自己试过哪些方法解决问题？
2. 你确定这是集群问题吗? 
3. 在提问之前要严格注意这里负责集群维护, 不负责(怎么调参/运行时间慢/不会配环境)

### 2. 复现问题细节
1. 你说明你使用的编程语言/平台了吗， 包括版本号？
2. 如果你的问题包含代码， 你是否已经改写成最小且完整的程序？
3. 如果你的代码不能编译， 问题中是否包含了编译错误信息？ 

### 3. 明确自身需求
1. 如果你的程序的输出结果和预期不同， 你是否说明了你的预期结果是什么， 你为什么这么想， 以及程序的实际结果？

运行/root/george目录下output_target_keras.py，出现标题中错误，详细错误信息在问题最后给出。
由于提示为usr/lib目录下文件问题，而非root目录，因此在提交该issue前没有尝试添加symlink等方法。

尝试了新建conda环境，并安装tesorflow和tensorflow-gpu，import tensorflow，问题复现，并初步定位了原因：
如果不进行ssh nodeXX操作，在admin下，无论是否安装tensorflow-gpu，
import tensorflow均会报错，
在node中，程序可以正常运行。

tensorflow版本号为1.9 and 1.11

详细错误信息如下：
Using TensorFlow backend.
Traceback (most recent call last):
  File "/root/Anacondas/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/Anacondas/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/Anacondas/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/Anacondas/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/root/Anacondas/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short

**Comment by piaozhx** [comment]
admin节点是供登录用的跳板节点, 上面没有显卡, 也没有显卡驱动, 为什么你要在admin运行tensorflow....

**Comment by persistz** [comment]
1. 9月份新管理系统上线之前可以在admin运行
2. node显存被占满时 自己会习惯在admin验证程序正确性

**Comment by piaozhx** [comment]
@persistz 尝试一下 #12 的解决方法

**Comment by persistz** [comment]
更新：使用#12的解决方法修复成功，并收到管理员警告，不要用cpu跑大程序:joy::joy:
@piaozhx 问题需要close吗？
