### ISSUE TITLE
添加反向代理和打开jupyter失败

### ISSUE THREAD

**Issue by Privilger** [piaozhx/DockerMonitor#9]
### 1. 查明问题原因
程序无法跑通有多种原因, 请严格走以下步骤:
1. 提问之前你做过研究吗？你是否说明了自己试过哪些方法解决问题？

Q1:
生成jupyter notebook的配置文件之后，
使用`ssh -CNfR 22220:0.0.0.0:22220 admin`   添加反向代理
报警告`Warning: remote port forwarding failed for listen port 22220`

Q2:
然后jupyter notebook --allow-root 报错
```shell
$ jupyter notebook --allow-root
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/usr/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1379, in init_webapp
    self.jinja_environment_options,
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 251, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```
根据错误`ValueError: '' does not appear to be an IPv4 or IPv6 address`推测是网络地址有问题，但是ifconfig命令正常。

Q3:
运行visdom失败
```shell
$ python -m visdom.server -p 22220
Downloading scripts. It might take a while.
It's Alive!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/visdom/server.py", line 1184, in <module>
    download_scripts_and_run()
  File "/usr/local/lib/python3.6/dist-packages/visdom/server.py", line 1180, in download_scripts_and_run
    main()
  File "/usr/local/lib/python3.6/dist-packages/visdom/server.py", line 1175, in main
    print_func=print_func, user_credential=user_credential)
  File "/usr/local/lib/python3.6/dist-packages/visdom/server.py", line 1113, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/usr/local/lib/python3.6/dist-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python3.6/dist-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
```
查过`OSError: [Errno 98] Address already in use`，大致是说端口被占用，让我找出占用端口的程序并`kill`，但是使用`ps -fA | grep python`并没有找到相关的程序。
综上所述，推测的原因是网络存在问题，之前曾使用`python -m visdom.server -p 30330 &`尝试让程序在后台运行，可是发现程序没有运行成功。后台也找不到该程序。

2. 你确定这是集群问题吗? 
不是集群问题，其他同学可以正常使用。
3. 在提问之前要严格注意这里负责集群维护, 不负责(怎么调参/运行时间慢/不会配环境)

### 2. 复现问题细节
1. 你说明你使用的编程语言/平台了吗， 包括版本号？
2. 如果你的问题包含代码， 你是否已经改写成最小且完整的程序？
3. 如果你的代码不能编译， 问题中是否包含了编译错误信息？ 

### 3. 明确自身需求
1. 如果你的程序的输出结果和预期不同， 你是否说明了你的预期结果是什么， 你为什么这么想， 以及程序的实际结果？
是否需要重启Docker或者重置Docker。

**Comment by piaozhx** [comment]
@youngfly11

**Comment by Privilger** [comment]
> 应该是你开的端口不对,你先试试改下端口。2xxxx都是给ssh登录用的,http://10.19.124.11:8899/cs280_permission 中的ADMIN_PORT才是向外开服务用的. @Privilger

果然是端口没设好，设置成ADMIN_PORT之后Q1成功解决，但是Q2和Q3还是一样的错误。_(:з」∠)_

**Comment by youngfly11** [comment]
1. for q3: 所有对外开服务的端口只能使用提供的admin_port的十个端口。
2. for q2: jupyter你是按照教程一步一步配置的吗？@Privilger

**Comment by Privilger** [comment]
> * for q3: 所有对外开服务的端口只能使用提供的admin_port的十个端口。
> * for q2: jupyter你是按照教程一步一步配置的吗？@Privilger

1. Q3也是用admin_port端口，但是还是报原来的错误。
2. 是的，之前我觉得我可能按教程配置没做好，还把jupyter_notebook_config.py删了重新走了一遍配置教程。我唯一做过的不同于教程的部分是运行了`python -m visdom.server -p 22220 &` ，让visdom在后台运行，但是当我查看后台时，并没有找到这个进程。

**Comment by youngfly11** [comment]
> > * for q3: 所有对外开服务的端口只能使用提供的admin_port的十个端口。
> > * for q2: jupyter你是按照教程一步一步配置的吗？@Privilger
> 
> 1. Q3也是用admin_port端口，但是还是报原来的错误。
> 2. 是的，之前我觉得我可能按教程配置没做好，还把jupyter_notebook_config.py删了重新走了一遍配置教程。我唯一做过的不同于教程的部分是运行了`python -m visdom.server -p 22220 &` ，让visdom在后台运行，但是当我查看后台时，并没有找到这个进程。

1. 你为啥要用visdom，你可能没有装visdom， 开启visdom后面的端口也是用admin_port的端口，除了都登陆的时候用 22220，其他任何时候都不要用这个。 python -m visdom.server -p 32205

**Comment by Privilger** [comment]
> > > * for q3: 所有对外开服务的端口只能使用提供的admin_port的十个端口。
> > > * for q2: jupyter你是按照教程一步一步配置的吗？@Privilger
> > 
> > 
> > 
> > 1. Q3也是用admin_port端口，但是还是报原来的错误。
> > 2. 是的，之前我觉得我可能按教程配置没做好，还把jupyter_notebook_config.py删了重新走了一遍配置教程。我唯一做过的不同于教程的部分是运行了`python -m visdom.server -p 22220 &` ，让visdom在后台运行，但是当我查看后台时，并没有找到这个进程。
> 
> 1. 你为啥要用visdom，你可能没有装visdom， 开启visdom后面的端口也是用admin_port的端口，除了都登陆的时候用 22220，其他任何时候都不要用这个。 python -m visdom.server -p 32205

用` pip install visdom`安装过visdom。最开始只是按照教程装visdom...并不是有需求装visdom...用 `python -m visdom.server -p 32205`现在已经成功运行(ﾟ▽ﾟ)/。之前试`python -m visdom.server -p 32200`不行的原因应该是我jupyter notebook占用了32200端口。那现在只剩下Q2了。_(:з」∠)_

**Comment by Privilger** [comment]
> 容器中执行命令是`jupyter notebook --port 30611 --ip=0.0.0.0 --allow-root`,加一个--ip=0.0.0.0试一下@Privilger

加上--ip=0.0.0.0 后成功运行\(^o^)/ ,Thanks♪(･ω･)ﾉ

**Comment by piaozhx** [comment]
[已更新文档](http://10.19.124.11:8898/QA_container/), 劝退涉事程序员
